---
- hosts: application
  become: yes
  vars:
    mysql_root_password: "jash1234"
    mysql_database: "webapp_db"
    mysql_user: "webapp_user"
    mysql_password: "jash1234"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MySQL and its dependencies
      apt:
        name:
          - mysql-server
          - mysql-client
          - python3-mysqldb
          - libmysqlclient-dev
        state: present

    - name: Enable MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create MySQL database
      mysql_db:
        name: "{{ mysql_database }}"
        state: present

    - name: Create MySQL user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_database }}.*:ALL"
        state: present

- hosts: database
  become: yes
  vars:
    app_repo_url: "/home/einfochips/Videos/Day17/Day17thsql/Project2/files/index.html"
    app_directory: "/var/www/html/"
    db_host: "{{ hostvars['db_server']['ansible_host'] }}"
    db_name: "webapp_db"
    db_user: "webapp_user"
    db_password: "secure_user_password"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Install PHP and extensions
      apt:
        name:
          - php
          - php-mysql
          - libapache2-mod-php
        state: present

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy Web Application
      ansible.builtin.copy:
        src: "{{ app_repo_url }}"
        dest: "{{ app_directory }}"

    - name: Deploy Apache configuration file
      template:
        src: /home/einfochips/Videos/Day17/Day17thsql/Project2/template/app_config.php.j2
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart Apache

    - name: Ensure appropriate permissions for application directory
      file:
        path: "{{ app_directory }}"
        owner: www-data
        group: www-data
        state: directory
        recurse: yes

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
